### ISSUE TITLE
Resize Form

### ISSUE THREAD

**Issue by justdan0227** [neoneye/SwiftyFORM#60]
Been using SwiftyForm for a month now and love it.  Is there a way to resize the form itself so that you could add things above the form - static labels or a segmentedcontrol?

**Comment by neoneye** [comment]
The entire form is transformed into `UITableViewCell's` and  fed into a `UITableView`.

Approach A: If you want the content to scrolls along with the UITableView, then a custom cell will have to be inserted into the top of the tableview. However cells with variable height is excruciating difficult. I think SwiftUI cleans up this mess.

Approach B: If you want content that is fixed in the top or bottom of the screen, then a UIView is to be inserted above UITableView.

**Comment by justdan0227** [comment]
Thanks!
