### ISSUE TITLE
Rounded Corners on Button Row

### ISSUE THREAD

**Issue by justdan0227** [neoneye/SwiftyFORM#62]
Is there a way to get access to the button layer to make the corners rounded so that it looks more like a button?

**Comment by neoneye** [comment]
A rounded corners button would indeed be handy. PRs are welcome.

I didn't make SwiftyFORM with theming in mind, since trends comes and goes. The default controls are Apple's style for the iOS version it's running on, ala the Settings app. For custom controls with custom theming then a custom control would have to be made.
